/**
 * Created by colten on 3/4/2016.
 */
public class Problem2_EvenFibonacciNumbers {
    public static void main(String[] args) {
        /**
         * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
         * By starting with 1 and 2, the first 10 terms will be:

         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

         By considering the terms in the Fibonacci sequence whose values do not exceed four million,
         find the sum of the even-valued terms.
         */

        int num1 = 1, num2 = 2, sum = 0, target = 4000000;

        do {
            if (num1%2 == 0)
                sum+=num1;
            if (num2%2 == 0)
                sum+=num2;
           // System.out.print(num1 + " " + num2);
            num1+=num2;
            num2+=num1;

        } while((num1<=target && num2 <= target));

        System.out.print(sum);
    }
}
